name: test

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version:
        - 20.x

    steps:
    - uses: actions/checkout@v4.1.0
    - name: Setup Node.js
      uses: actions/setup-node@v3.8.1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm test
      env:
        CI: true
